# Generated by Django 5.0.3 on 2026-06-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_prediction_shapexplanation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shapexplanation',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='labreport',
            name='pdf_file_path',
            field=models.CharField(blank=True, help_text='Relative path to uploaded PDF file from MEDIA_ROOT', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='pdf_upload_timestamp',
            field=models.DateTimeField(blank=True, help_text='When the PDF file was uploaded', null=True),
        ),
    ]
